user_registration:
    path:     /login
    defaults: { _controller: AppBundle:Invest:register }
logged_in:
    path:    /
    defaults: {_controller: AppBundle:Invest:main }
invest:
    path:    /invest
    defaults: { _controller: AppBundle:Invest:invest }
loan:
    path:    /loan
    defaults: { _controller: AppBundle:Loan:giveLoan }
companylist:
    path:    /companies
    defaults: { _controller: AppBundle:Main:getCompanies }
invest_to_company:
    path:    /invest/{company}
    defaults: { _controller: AppBundle:Main:invest }
loan_to_company:
    path: /loan/{company}
    defaults: { _controller: AppBundle:Main:Loan }
logout:
    path: /logout