user_registration:
    path:     /login
    defaults: { _controller: AppBundle:Invest:register }
logged_in:
    path:    /
    defaults: {_controller: AppBundle:Invest:main }
invest:
    path:    /invest
    defaults: { _controller: AppBundle:Invest:invest }